[package]
name = "FlashCardsGui"
version = "0.1.0"
edition = "2021"

[dependencies]
flash_card_parser = { git = "https://github.com/Lukas412/FlashCardParser.git" }
xilem = { git = "https://github.com/linebender/xilem.git" }
